version: '3.8'

services:
  mongo1:
    image: mongo:4.4.3
    hostname: mongo1
    container_name: mongo1
    volumes:
      - data/db
    ports:
      - 30001:27017
    networks:
      - imdb
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo2:
    image: mongo:4.4.3
    hostname: mongo2
    container_name: mongo2
    ports:
      - 30002:27017
    networks:
      - imdb
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongo3:
    image: mongo:4.4.3
    hostname: mongo3
    container_name: mongo3
    ports:
      - 30003:27017
    networks:
      - imdb
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

  mongosetup:
    image: mongo:4.4.3
    container_name: mongosetup
    networks:
      - imdb
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    restart: "no"
    volumes:
      - ./scripts:/scripts
    entrypoint: [ "/scripts/mongo-cluster-setup.sh" ]

  imdb-rest-api:
    container_name: rest-api
    build: ./
    depends_on:
      - mongosetup
    ports:
      - 8080:8080
    networks:
      - imdb

networks:
  imdb: